ATM/Controllers/CheckingAccountController.cs
using ATM.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ATM.Controllers
{
    public class CheckingAccountController : Controller
    {
        // GET: ChekingAccount
        public ActionResult Index()
        {
            return View();
        }

        // GET: ChekingAccount/Details/5
        public ActionResult Details()
        {
            var checkingAccount = new CheckingAccount { id=1 ,AccountNumber = "32232", FirstName = "Michael", LastName = "Chakj", Balance = 500 };
            return View(checkingAccount);
        }

        // GET: ChekingAccount/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ChekingAccount/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ChekingAccount/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ChekingAccount/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ChekingAccount/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ChekingAccount/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ATM/Controllers/HomeController.cs
using ATM.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace ATM.Controllers
{
    public class HomeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        [Authorize]
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            var checkingAccountId = db.CheckingAccounts.Where(c => c.ApplicationUserId == userId).First().id;
            ViewBag.CheckingAccountId = checkingAccountId;
            return View();
        }
        [HttpGet]
        public ActionResult About()
        {
            ViewBag.TheMessage = "Left your message ";

            return View();
        }

        [HttpPost]
        public ActionResult About(string message)
        {
            ViewBag.TheMessage = "Thank you we will contact";

            return View();
        }
        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ATM/Controllers/TransactionController.cs
using ATM.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ATM.Controllers
{
    public class TransactionController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Transaction
        public ActionResult Index()
        {
            return View();
        }
        [Authorize]
        public ActionResult Deposit(int checkingAccountId  )
        {
            return View();
        }

    [HttpPost]
        public ActionResult Deposit(Transaction transaction)
        {
        if(ModelState.IsValid)
        {
            db.Transactions.Add(transaction);
            db.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
            return View();
        }
    }
}

ATM/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.TheMessage</h3>

<form method="post">
    <textarea name="message"> </textarea>
    <input type="submit" value="send"/>
</form>

ATM/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ATM/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="row">
    <div class="col-md-6 margin-top-20">
        <a href="#" class="btn btn-primary btn-large btn-block "><span class="glyphicon glyphicon-arrow-down"></span> Withdrawal</a>
        <a href="#" class="btn btn-primary btn-large btn-block "><span class="glyphicon glyphicon-flash"></span> Quick Cash 100$</a>
        <a href="@Url.Action("Details","CheckingAccount")" class="btn btn-primary btn-large btn-block "><span class="glyphicon glyphicon-question-sign"></span> Balance Inquiry</a>
        <a href="#" class="btn btn-primary btn-large btn-block "><span class="glyphicon glyphicon-print"></span> Print Statement</a>
        <a href="#" class="btn btn-primary btn-large btn-block "><span class="glyphicon glyphicon-transfer"></span> Transfer Funds</a>
        <a href="@Url.Action("Deposit", "Transaction", new { checkingAccountId = ViewBag.CheckingAccountId })" class="btn btn-primary btn-large btn-block "><span class="glyphicon glyphicon-arrow-up"></span> Deposit</a>

    </div>
</div>

@{var amounts = new List<Decimal> { 100, 25.50m, -40, 2777 };
}
<ul>
    @foreach (decimal amount in amounts)
    {

        <li>@formatAmount(amount)</li>
    }
</ul>

@helper formatAmount(decimal amount)
{
    var color = "green";
    if (amount < 0)
        
    {
        color = "red";
    }
    <span style="color:@color">@String.Format("{0:c}", amount)</span>
}